# Generated by Django 6.0.1 on 2026-02-04 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('finance', 'Finance'), ('hr', 'HR'), ('marketing', 'Marketing'), ('engineering', 'Engineering'), ('staff', 'Staff')], max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('intern', 'Intern'), ('employee', 'Employee'), ('manager', 'Manager'), ('ceo', 'CEO'), ('auditor', 'Auditor')], max_length=15),
        ),
    ]
