# Generated by Django 6.0.1 on 2026-02-04 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_name', models.CharField(max_length=20, unique=True)),
                ('action', models.CharField(choices=[('read', 'Read'), ('write', 'Write'), ('delete', 'Delete'), ('update', 'Update')], default=None, max_length=10)),
                ('resource_type', models.CharField(choices=[('report', 'Report'), ('file', 'File'), ('record', 'Record')], max_length=10)),
                ('effect', models.CharField(choices=[('allow', 'Allow'), ('deny', 'Deny')], default=None, max_length=10)),
                ('priority', models.IntegerField()),
                ('conditions', models.JSONField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policies_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policies_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('policy_name', 'resource_type', 'action')},
            },
        ),
    ]
