# Generated by Django 6.0.1 on 2026-02-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='policy_name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
