# Generated by Django 6.0.1 on 2026-02-04 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit_log', '0001_initial'),
        ('decision_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='decision',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_decisions', to='decision_engine.decision'),
        ),
    ]
