# Generated by Django 6.0.1 on 2026-02-04 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('allow', 'Allow'), ('deny', 'Deny')], default=None, max_length=15)),
                ('reason', models.TextField(max_length=150)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
