# Generated by Django 6.0.1 on 2026-02-04 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('decision_engine', '0001_initial'),
        ('policy_engine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='decision',
            name='policy_used',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies_decisions', to='policy_engine.policy'),
        ),
        migrations.AddField(
            model_name='decision',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_decisions', to=settings.AUTH_USER_MODEL),
        ),
    ]
