# Generated by Django 6.0.1 on 2026-02-04 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decision_engine', '0002_initial'),
        ('policy_engine', '0002_alter_policy_policy_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='decision',
            name='policy_used',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policies_decisions', to='policy_engine.policy'),
        ),
        migrations.AlterField(
            model_name='decision',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_decisions', to=settings.AUTH_USER_MODEL),
        ),
    ]
