# Generated by Django 6.0.1 on 2026-02-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decision_engine', '0003_alter_decision_policy_used_alter_decision_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='decision',
            name='action',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='decision',
            name='resource',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
