# Generated by Django 6.0.1 on 2026-02-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decision_engine', '0004_decision_action_decision_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decision',
            name='reason',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
    ]
